// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxqytgljytudlxgparyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cXl0Z2xqeXR1ZGx4Z3BhcnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzA4NjYsImV4cCI6MjA2OTAwNjg2Nn0.RLGjxPqWW4cdaoHEpuRcU5pWnj2pS8ZU_MzjYqnVWBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});